apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: GROQ_API_KEY
            - name: GSUITE_CREDS_FILE
            - name: KAFKA_BROKER
              value: kafka1:29092
            - name: KAFKA_TOPIC
              value: emails
            - name: NEO4J_DB_HOST
              value: docker-neo4j-1
            - name: NEO4J_PASSWORD
            - name: NEO4J_URI
              value: docker-neo4j-1:7474
            - name: NEO4J_USERNAME
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: VECTOR_DB_HOST
              value: docker-weaviate-1
            - name: VECTOR_DB_PORT
              value: "8080"
          image: context-api:0.1.1
          name: api
          ports:
            - containerPort: 5010
              protocol: TCP
            - containerPort: 3127
              protocol: TCP
      restartPolicy: Always
