apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: document-processor
  name: document-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: document-processor
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: document-processor
    spec:
      containers:
        - env:
            - name: GROQ_API_KEY
            - name: KAFKA_BROKER
              value: kafka1:29092
            - name: KAFKA_TOPIC
              value: documents
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: VECTOR_DB_HOST
              value: docker-weaviate-1
            - name: VECTOR_DB_PORT
              value: "8080"
          image: document-processor:0.1.1
          name: document-processor
      restartPolicy: Always
