apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: event-processor
  name: event-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: event-processor
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: event-processor
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka1:29092
            - name: KAFKA_TOPIC
              value: calendar
            - name: NEO4J_DB_HOST
              value: docker-neo4j-1
            - name: NEO4J_DB_PORT
              value: "7687"
            - name: NEO4J_PASSWORD
            - name: NEO4J_USERNAME
            - name: PYTHONUNBUFFERED
              value: "1"
          image: event-processor:0.1.1
          name: event-processor
      restartPolicy: Always
