apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - env:
            - name: NEO4JLABS_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_apoc_export_file_enabled
              value: "true"
            - name: NEO4J_apoc_import_file_enabled
              value: "true"
            - name: NEO4J_apoc_import_file_use__neo4j__config
              value: "true"
          image: neo4j:5.22.0
          name: neo4j
          ports:
            - containerPort: 7687
              protocol: TCP
            - containerPort: 7474
              protocol: TCP
      restartPolicy: Always
