apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: processor
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processor
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: processor
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: host.docker.internal:29092
            - name: KAFKA_TOPIC
              value: emails
            - name: NEO4J_DB_HOST
              value: docker-neo4j-1
            - name: NEO4J_DB_PORT
              value: "7687"
            - name: NEO4J_PASSWORD
            - name: NEO4J_USERNAME
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: VECTOR_DB_HOST
              value: docker-weaviate-1
            - name: VECTOR_DB_PORT
              value: "8080"
          image: context-processor:0.1.1
          name: processor
      restartPolicy: Always
