apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: reranker-transformers
  name: reranker-transformers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reranker-transformers
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: reranker-transformers
    spec:
      containers:
        - env:
            - name: ENABLE_CUDA
              value: "0"
          image: cr.weaviate.io/semitechnologies/reranker-transformers:cross-encoder-ms-marco-MiniLM-L-6-v2
          name: reranker-transformers
      restartPolicy: Always
