apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: t2v-transformers
  name: t2v-transformers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: t2v-transformers
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: t2v-transformers
    spec:
      containers:
        - env:
            - name: ENABLE_CUDA
              value: "0"
          image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
          name: t2v-transformers
      restartPolicy: Always
