apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: weaviate
  name: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weaviate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: weaviate
    spec:
      containers:
        - env:
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: CLUSTER_HOSTNAME
              value: weaviate-1
            - name: DEFAULT_VECTORIZER_MODULE
              value: text2vec-transformers
            - name: ENABLE_MODULES
              value: text2vec-transformers,reranker-transformers
            - name: PERSISTENCE_DATA_PATH
              value: /var/lib/weaviate
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: RERANKER_INFERENCE_API
              value: http://reranker-transformers:8080
            - name: TRANSFORMERS_INFERENCE_API
              value: http://t2v-transformers:8080
          image: cr.weaviate.io/semitechnologies/weaviate:1.24.4
          name: weaviate
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50051
              protocol: TCP
      restartPolicy: Always
